name: Build (onedir) and package

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install openpyxl tqdm pyinstaller
          }

      - name: Build (onedir, no upx)
        run: |
          pyinstaller --onedir --name "excel_split_to_sheets" --noupx --clean excel_split_to_sheets.py

      - name: Zip artifact
        shell: pwsh
        run: |
          $zip = "excel-split-to-sheets-win.zip"
          Compress-Archive -Path "dist/excel_split_to_sheets/*" -DestinationPath $zip -Force
          Write-Host "Zipped to $zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-split-to-sheets-windows
          path: |
            excel-split-to-sheets-win.zip
