name: Build EXE (Excel split to sheets)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install openpyxl tqdm pyinstaller
          }

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name "excel_split_to_sheets" excel_split_to_sheets.py

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: excel-split-to-sheets-windows
          path: dist/excel_split_to_sheets.exe
          if-no-files-found: warn
