# .github/workflows/build-windows-exe.yml
name: Build Windows EXE

on:
  workflow_dispatch:          # 手动触发；也可改 push

jobs:
  build:
    runs-on: windows-latest   # 微软托管的 Windows Server 2022 x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pypdf tqdm pyinstaller

      - name: Build single‑file EXE
        run: |
          pyinstaller --onefile reorder_invoices.py --name reorder_invoices_win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/reorder_invoices_win.exe
