name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.8.0
          pip install openpyxl==3.1.3 tqdm==4.66.4

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --noconfirm --clean --onefile --name sheets_split_to_excel sheets_split_to_excel.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sheets_split_to_excel-windows
          path: dist/sheets_split_to_excel.exe
          if-no-files-found: error
          retention-days: 14

      - name: Create GitHub Release (when tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/sheets_split_to_excel.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
