name: Build EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install pandas openpyxl pyinstaller
          }

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name "Excel按人拆分" split_by_person.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Excel按人拆分-windows
          path: dist/**
